# Generated by Django 3.1 on 2021-05-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
