# Generated by Django 3.1 on 2021-05-19 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_todo', '0002_cat_name_uniqe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_category', to='my_todo.category'),
        ),
    ]
